### ISSUE TITLE
Problems with Routing

### ISSUE THREAD

**Issue by noxify** [FbF/Laravel-Blog#6]
Hi guys,

currently i'm trying the administrator package in my Lavaral 4.1 environment (local, OSX, PHP 5.4.4).

I've run the fakeSeeder to get some demo content - okay
The backend it also working.

But even when i try to show the blog post in the frontend, i got an 

```
Symfony \ Component \ HttpKernel \ Exception \ NotFoundHttpException
```

I've tested it with the following url:
http://localhost:8888/< project-name >/public/index.php/blog/molestias-praesentium

My composer.json looks like

```
{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "require": {
        "laravel/framework": "4.1.*",
        "frozennode/administrator": "dev-master",
        "fbf/laravel-pages": "dev-master",
        "cartalyst/sentry": "2.0.*",
        "fbf/laravel-blog": "dev-master"
    },
    "autoload": {
        "classmap": [
            "app/commands",
            "app/controllers",
            "app/models",
            "app/database/migrations",
            "app/database/seeds",
            "app/tests/TestCase.php"
        ]
    },
    "scripts": {
        "post-install-cmd": [
            "php artisan clear-compiled",
            "php artisan optimize",
            "php artisan asset:publish frozennode/administrator"
        ],
        "post-update-cmd": [
            "php artisan clear-compiled",
            "php artisan optimize",
            "php artisan asset:publish frozennode/administrator"
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ]
    },
    "config": {
        "preferred-install": "dist"
    },
    "minimum-stability": "dev"
}
```

The log file is the following

```
[2014-02-04 15:52:12] production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /Applications/MAMP/htdocs/<projectname>/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:871
Stack trace:
#0 /Applications/MAMP/htdocs/<projectname>/workbench/pseudoagentur/users/vendor/illuminate/support/Illuminate/Support/Facades/Facade.php(208): Illuminate\Foundation\Application->abort(404)
#1 /Applications/MAMP/htdocs/<projectname>/vendor/fbf/laravel-pages/src/controllers/PagesController.php(21): Illuminate\Support\Facades\Facade::__callStatic('abort', Array)
#2 /Applications/MAMP/htdocs/<projectname>/vendor/fbf/laravel-pages/src/controllers/PagesController.php(21): Illuminate\Support\Facades\App::abort(404)
#3 [internal function]: Fbf\LaravelPages\PagesController->view('blog/molestias-...')
#4 /Applications/MAMP/htdocs/<projectname>/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(194): call_user_func_array(Array, Array)
#5 /Applications/MAMP/htdocs/<projectname>/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('view', Array)
#6 /Applications/MAMP/htdocs/<projectname>/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(Fbf\LaravelPages\PagesController), Object(Illuminate\Routing\Route), 'view')
#7 /Applications/MAMP/htdocs/<projectname>/vendor/laravel/framework/src/Illuminate/Routing/Router.php(934): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Fbf\LaravelPage...', 'view')
#8 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('blog/molestias-...')
#9 /Applications/MAMP/htdocs/<projectname>/vendor/laravel/framework/src/Illuminate/Routing/Route.php(105): call_user_func_array(Object(Closure), Array)
#10 /Applications/MAMP/htdocs/<projectname>/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1000): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#11 /Applications/MAMP/htdocs/<projectname>/vendor/laravel/framework/src/Illuminate/Routing/Router.php(968): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#12 /Applications/MAMP/htdocs/<projectname>/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(738): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#13 /Applications/MAMP/htdocs/<projectname>/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(708): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#14 /Applications/MAMP/htdocs/<projectname>/vendor/laravel/framework/src/Illuminate/Http/FrameGuard.php(38): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#15 /Applications/MAMP/htdocs/<projectname>/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Illuminate\Http\FrameGuard->handle(Object(Illuminate\Http\Request), 1, true)
#16 /Applications/MAMP/htdocs/<projectname>/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#17 /Applications/MAMP/htdocs/<projectname>/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#18 /Applications/MAMP/htdocs/<projectname>/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#19 /Applications/MAMP/htdocs/<projectname>/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(606): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#20 /Applications/MAMP/htdocs/<projectname>/public/index.php(49): Illuminate\Foundation\Application->run()
#21 {main} [] []
```

Hope you can help me. 
Thanks!

**Comment by noxify** [comment]
Okay after reading the log again and again and again I found the problem :)

app.php --> providers before:

```
        'Frozennode\Administrator\AdministratorServiceProvider',
        'Fbf\LaravelPages\LaravelPagesServiceProvider',
        'Cartalyst\Sentry\SentryServiceProvider',
        'Fbf\LaravelBlog\LaravelBlogServiceProvider'
```

app.php --> providers after:

```
        'Frozennode\Administrator\AdministratorServiceProvider',
        'Fbf\LaravelBlog\LaravelBlogServiceProvider',
        'Fbf\LaravelPages\LaravelPagesServiceProvider',
        'Cartalyst\Sentry\SentryServiceProvider',

```

and it works fine (means i got now the error message, that the layout does not exists :D )
